import streamlit as st

st.title("FAQ & Definitions")

# Assistance Section
st.markdown("### 📚 Assistance & Key Definitions")
with st.expander("Understanding Portfolio Management Metrics", expanded=True):
    st.markdown("""
    #### What is a Portfolio Fund?
    A **portfolio fund** is a collection of investments (stocks, bonds, etc.) managed by a professional portfolio manager. 
    Think of it as a basket of investments that the manager buys and sells on behalf of investors.
    
    #### Key Performance Metrics
    
    **1. Performance (Returns)**
    - Shows how much the fund has gained or lost over a period (1 year, 3 years, etc.)
    - Expressed as a percentage (e.g., 10% means the fund grew by 10%)
    - **Higher is better** - you want funds that make money
    
    **2. Volatility (Risk)**
    - Measures how much the fund's value goes up and down
    - High volatility = more unpredictable, more risk
    - Low volatility = more stable, less risk
    - Expressed as a percentage - **lower is generally better** for stability
    
    **3. Excess Return**
    - Shows how much better (or worse) the fund performed compared to its benchmark
    - Benchmark = a standard index (like the S&P 500) that represents the market
    - **Positive excess return** = fund beat the market (good!)
    - **Negative excess return** = fund underperformed the market (bad)
    
    **4. Sharpe Ratio**
    - Measures risk-adjusted returns: "How much return did I get for the risk I took?"
    - **Higher is better** - means better returns relative to the risk taken
    - A Sharpe ratio above 1 is generally considered good
    
    **5. Tracking Error**
    - Measures how much the fund's performance differs from its benchmark
    - Lower tracking error = fund follows the benchmark more closely
    - Higher tracking error = fund deviates more from the benchmark
    
    **6. AUM (Assets Under Management)**
    - Total amount of money the fund manages
    - Larger AUM often indicates investor confidence and fund success
    - In this dashboard, AUM values with "M" stand for **millions** (e.g., "100M" = €100 million)
    - AUM is a key factor in calculating fund revenues (see Revenue calculation below)
    
    **6a. Fees**
    - The percentage charged by the fund management company for managing the investments
    - Typically expressed as an annual percentage (e.g., 1.5% per year)
    - Fees are charged on the total AUM
    - Example: A fund with 1.5% fees charges €1.50 for every €100 managed per year
    
    **6b. Revenue Calculation**
    - **Fund Revenue = AUM × Fees**
    - This represents the annual income generated by the fund management company
    - **Example Calculation:**
      - If a fund has AUM of €100M (€100,000,000)
      - And charges fees of 1.5% per year
      - Revenue = €100,000,000 × 0.015 = **€1,500,000 per year**
    - Revenue is important because it shows how much money the fund generates, which can be a factor in bonus allocation decisions
    - Higher revenue funds may indicate successful fund management and investor attraction
    
    **7. Peer Ranking**
    - Compares the fund's performance to similar funds
    - Ranking of **1** = best performer in the category
    - Ranking of **100** = worst performer in the category
    - **Lower numbers are better**
    
    **8. Rating**
    - Overall quality score of the fund (out of 5)
    - **5 = highest rating** (excellent fund)
    - Considers multiple factors: performance, risk, consistency
    
    **9. ESG Score (E Score)**
    - Measures the fund's **Environmental** impact
    - Part of ESG (Environmental, Social, Governance) criteria
    - **Lower scores are better** (better environmental practices)
    - Important for sustainable and responsible investing
    """)